### ISSUE TITLE
Copy-rename is performing a move

### ISSUE THREAD

**Issue by terenceingram** [coderplus/copy-rename-maven-plugin#1]
I am trying out the plugin but the plugin is actually moving my file instead of copying it. I assumed it would leave my file and copy and rename it.

**Comment by aneesh-joseph** [comment]
The `rename` goal will do a rename even if the target file is in a different directory. So yes you can say that it does a move.

If you want to copy a file to a different target name, you can use the `copy` goal instead.

See the first example on the [usage page](https://coderplus.github.io/copy-rename-maven-plugin/usage.html)

**Comment by terenceingram** [comment]
Thanks. For that.
