### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by karolmie1** [coderplus/copy-rename-maven-plugin#12]
Hey!
On your webpage, and on maven central there is stated that license is MIT, while in repository there is commited Eclipse license, and in pom there is MIT licence.

Could you please clarify the confusion?

http://coderplus.github.io/copy-rename-maven-plugin/license.html
https://mvnrepository.com/artifact/com.coderplus.maven.plugins/copy-rename-maven-plugin/1.0

**Comment by aneesh-joseph** [comment]
thank you , sorted it now on master :smile:
